apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grocery-genie-data-pvc
  namespace: staging
  labels:
    app: grocery-genie
    environment: staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grocery-genie-logs-pvc
  namespace: staging
  labels:
    app: grocery-genie
    environment: staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grocery-genie-raw-pvc
  namespace: staging
  labels:
    app: grocery-genie
    environment: staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
