[tool.ruff]
# Maximum line length (for context, not enforced if E501 is ignored)
line-length = 100

# Apply Ruff formatting (optional but recommended)
[tool.ruff.format]
# Enables auto-formatting with `ruff format`
quote-style = "double"
line-ending = "lf"

[tool.ruff.lint]
# Default linting rules that are widely accepted and useful
select = [
  "E",    # pycodestyle (errors)
  "F",    # pyflakes
  "W",    # pycodestyle (warnings)
  "I",    # isort (import order)
  "N",    # pep8-naming
  "UP",   # pyupgrade
  "B",    # flake8-bugbear
  "C4",   # flake8-comprehensions
  "SIM",  # flake8-simplify
]

# Ignore nitpicky or redundant rules
extend-ignore = [
  "PLC0415",  # allow local imports inside functions
  "E501",     # don't enforce line length (optional)
]

# Optionally exclude tests or migrations
exclude = [
  "migrations/*",
  "tests/*",
]
