apiVersion: v1
kind: Service
metadata:
  name: grocery-genie-service
  labels:
    app: grocery-genie
spec:
  selector:
    app: grocery-genie
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
  type: ClusterIP
